//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgoraVaiRecursosHumanos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Horas
    {
        public int Id { get; set; }
        public int Horas1 { get; set; }
        public string Periodo { get; set; }
        public Nullable<int> Funcionario { get; set; }
    
        public virtual Funcionarios Funcionarios { get; set; }
    }
}
